# Generated by Django 4.0.6 on 2022-08-03 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('sponsor_type', models.CharField(choices=[('JISMONIY SHAXS', 'JISMONIY SHAXS'), ('YURIDIK SHAXS', 'YURIDIK SHAXS')], default='JISMONIY SHAXS', max_length=32)),
                ('sponsor_status', models.CharField(choices=[('YANGI', 'YANGI'), ('TASDIQLANGAN', 'TASDIQLANGAN'), ('BEKOR QILINGAN', 'BEKOR QILINGAN'), ('MODERATSIYADA', 'MODERATSIYADA')], default='YANGI', max_length=32)),
                ('full_name', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=16)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=21)),
                ('organization', models.CharField(max_length=128, null=True)),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sponsors', to='sponsor.paymenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
