# Generated by Django 4.0.6 on 2022-08-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_type',
            field=models.CharField(max_length=64),
        ),
    ]
