# Generated by Django 4.0.6 on 2022-08-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0002_alter_sponsor_sponsor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='created_datetime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='modified_datetime',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='created_datetime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='modified_datetime',
            field=models.DateField(auto_now=True),
        ),
    ]
