# Generated by Django 4.0.6 on 2022-08-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_sponsor_alter_payment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_datetime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='modified_datetime',
            field=models.DateField(auto_now=True),
        ),
    ]
