# Generated by Django 4.0.6 on 2022-08-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_otm_alter_student_student_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otm',
            name='created_datetime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='otm',
            name='modified_datetime',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_datetime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='modified_datetime',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studenttype',
            name='created_datetime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studenttype',
            name='modified_datetime',
            field=models.DateField(auto_now=True),
        ),
    ]
